# Generated by Django 5.1.5 on 2025-02-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='user_id',
            new_name='user',
        ),
    ]
