# Generated by Django 5.1.5 on 2025-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_session_id_basket_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='session',
        ),
        migrations.AddField(
            model_name='basket',
            name='session_key',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
