# Generated by Django 5.1.5 on 2025-03-10 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_remove_basket_session_basket_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='session_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
