# Generated by Django 5.1.5 on 2025-03-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_basket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='session_key',
            new_name='basket_key',
        ),
    ]
