# Generated by Django 5.1.5 on 2025-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_rename_session_key_basket_basket_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
