# Generated by Django 5.1.5 on 2025-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_alter_basket_basket_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['pk']},
        ),
    ]
