# Generated by Django 5.1.5 on 2025-03-17 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_alter_basket_options_alter_basketitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
