# Generated by Django 5.1.5 on 2025-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_alter_basket_basket_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
