# Generated by Django 5.1.5 on 2025-03-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_alter_basket_basket_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['pk'], 'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['pk'], 'verbose_name': 'Basket item', 'verbose_name_plural': 'Baskets items'},
        ),
    ]
