# Generated by Django 5.1.5 on 2025-02-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
