# Generated by Django 5.1.5 on 2025-02-11 10:11

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_product_image_to),
        ),
    ]
