# Generated by Django 5.1.5 on 2025-02-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk', 'title']},
        ),
    ]
