# Generated by Django 5.1.5 on 2025-02-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
