# Generated by Django 5.1.5 on 2025-02-14 12:52

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_reviews_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_category_image_to)),
                ('alt', models.CharField(default='Not Found.', max_length=100)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.category')),
            ],
        ),
    ]
