# Generated by Django 5.1.5 on 2025-02-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_image_productimage_categoryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
