# Generated by Django 5.1.5 on 2025-02-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_category_options_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['pk', 'product'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='specifications',
            options={'ordering': ['pk', 'product'], 'verbose_name': 'Specification', 'verbose_name_plural': 'Specifications'},
        ),
    ]
