# Generated by Django 5.1.5 on 2025-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_reviews_options_alter_specifications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
