# Generated by Django 5.1.5 on 2025-03-18 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_sort_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort_index',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
