# Generated by Django 5.1.5 on 2025-03-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_product_sort_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sort_index',
            new_name='sortIndex',
        ),
        migrations.AddField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False),
        ),
    ]
