# Generated by Django 5.1.5 on 2025-03-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dateFrom', models.DateField(auto_now_add=True)),
                ('dateTo', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.product')),
            ],
        ),
    ]
