# Generated by Django 5.1.5 on 2025-03-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_saleproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproducts',
            options={'verbose_name': 'Sale Product', 'verbose_name_plural': 'Sale Products'},
        ),
    ]
