# Generated by Django 5.1.5 on 2025-03-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_saleproducts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproducts',
            options={'ordering': ['pk', 'product'], 'verbose_name': 'Sale Product', 'verbose_name_plural': 'Sale Products'},
        ),
    ]
