# Generated by Django 5.1.5 on 2025-03-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_category_isdeleted_product_isdeleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'ordering': ['pk'], 'verbose_name': 'Category image', 'verbose_name_plural': 'Category images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['pk'], 'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['pk', 'name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
