# Generated by Django 5.1.5 on 2025-03-20 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0025_alter_saleproducts_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)])),
                ('deliveryType', models.CharField(max_length=4)),
                ('paymentType', models.CharField(max_length=7)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(related_name='order', to='catalog.product')),
            ],
        ),
    ]
