# Generated by Django 5.1.5 on 2025-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_products_orderitem_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
