# Generated by Django 5.1.5 on 2025-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
