# Generated by Django 5.1.5 on 2025-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_deliverytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCreated',
            field=models.BooleanField(default=False),
        ),
    ]
