# Generated by Django 5.1.5 on 2025-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_deliverytype_alter_order_paymenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPayed',
            field=models.BooleanField(default=False),
        ),
    ]
