# Generated by Django 5.1.5 on 2025-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_shop', '0003_alter_profile_email_alter_profile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
