# Generated by Django 5.1.5 on 2025-03-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_shop', '0004_profile_isdeleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk', 'user'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['pk'], 'verbose_name': 'Profile image', 'verbose_name_plural': 'Profile images'},
        ),
    ]
